# Header

menu:
  ä¸»é¡µ: /
  å½’æ¡£: /archives
  éšç¬”: /tags/è†œæ³•/
  ç›¸å†Œ: photo
tags: /tags

# SubNav
subnav:
  github: "https://github.com/FireYao"
  weibo: "http://weibo.com/u/3947710349"
  rss: "#"
  zhihu: "https://www.zhihu.com/people/long-li-qi-8"
#  qq: "936833764"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
#  bilibili: "http://space.bilibili.com/2943336"
#  acfun: "#"
#  mail: "lly_liuliyuan@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# æ˜¯å¦éœ€è¦ä¿®æ”¹ root è·¯å¾„
# å¦‚æœæ‚¨çš„ç½‘ç«™å­˜æ”¾åœ¨å­ç›®å½•ä¸­ï¼Œä¾‹å¦‚ http://yoursite.com/blogï¼Œ
# è¯·å°†æ‚¨çš„ url è®¾ä¸º http://yoursite.com/blog å¹¶æŠŠ root è®¾ä¸º /blog/ã€‚
root:

# Content

# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—
excerpt_link: 'ğŸ‘‡ğŸ‘‡ğŸ‘‡'
# æ–‡ç« å¡ç‰‡å³ä¸‹è§’å¸¸é©»é“¾æ¥ï¼Œä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
show_all_link: 'å±•å¼€å…¨æ–‡'
# æ•°å­¦å…¬å¼
mathjax: false
# æ˜¯å¦åœ¨æ–°çª—å£æ‰“å¼€é“¾æ¥
open_in_new: false

# æ‰“èµ
# è¯·åœ¨éœ€è¦æ‰“èµçš„æ–‡ç« çš„mdæ–‡ä»¶å¤´éƒ¨ï¼Œè®¾ç½®å±æ€§reward: true

# æ‰“èµåŸºç¡€è®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 1
# æ‰“èµwording
reward_wording: 'è°¢è°¢ä½ è¯·æˆ‘åƒç³–æœ'
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®å¤´åƒçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/assets/img/alipay.jpg
alipay:
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: /assets/img/weixin.png

# Miscellaneous
baidu_analytics: 'f0c20ae453637839060232a5dba73a2e'
google_analytics: ''
favicon: /assets/img/favicon.png

#ä½ çš„å¤´åƒurl
avatar: /assets/img/headImg/head_1.JPG

#æ˜¯å¦å¼€å¯åˆ†äº«
share_jia: true

#è¯„è®ºï¼š1ã€å¤šè¯´ï¼›2ã€ç½‘æ˜“äº‘è·Ÿå¸–ï¼›3ã€ç•…è¨€ï¼›4ã€Disqus ä¸éœ€è¦ä½¿ç”¨æŸé¡¹ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
#å…·ä½“è¯·å‚è€ƒwikiï¼šhttps://github.com/litten/hexo-theme-yilia/wiki/

#1ã€å¤šè¯´
duoshuo: false

#2ã€ç½‘æ˜“äº‘è·Ÿå¸–
wangyiyun: 'abec45d25f204bb18e8301822b98234e'

#3ã€ç•…è¨€
changyan_appid: false
changyan_conf: false

#4ã€Disqus åœ¨hexoæ ¹ç›®å½•çš„configé‡Œä¹Ÿæœ‰disqus_shortnameå­—æ®µï¼Œä¼˜å…ˆä½¿ç”¨yiliaçš„
disqus: false

# æ ·å¼å®šåˆ¶ - ä¸€èˆ¬ä¸éœ€è¦ä¿®æ”¹ï¼Œé™¤éæœ‰å¾ˆå¼ºçš„å®šåˆ¶æ¬²æœ›â€¦
style:
  # å¤´åƒä¸Šé¢çš„èƒŒæ™¯é¢œè‰²
  header: '#4d4d4d'
  # å³æ»‘æ¿å—èƒŒæ™¯
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# sliderçš„è®¾ç½®
slider:
  # æ˜¯å¦é»˜è®¤å±•å¼€tagsæ¿å—
  showTags: true

# æ™ºèƒ½èœå•
# å¦‚ä¸éœ€è¦ï¼Œå°†è¯¥å¯¹åº”é¡¹ç½®ä¸ºfalse
# æ¯”å¦‚
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'æ‰€æœ‰æ–‡ç« '
  friends: 'å‹é“¾'
  aboutme: 'å…³äºæˆ‘'

friends:
  å‹æƒ…é“¾æ¥1: https://fireyao.github.io/
  å‹æƒ…é“¾æ¥2: https://fireyao.github.io/

aboutme: å¾ˆæƒ­æ„§<br><br>åªåšäº†ä¸€ç‚¹å¾®å°çš„å·¥ä½œ<br>è°¢è°¢å¤§å®¶
